apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-gateway
  namespace: '1080781728713'
  selfLink: /apis/serving.knative.dev/v1/namespaces/1080781728713/services/api-gateway
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/network-interfaces: '[{"network":"courtiq","subnetwork":"us-central1"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only

    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1080781728713-compute@developer.gserviceaccount.com
      containers:
      - name: api-gateway
        image: us-central1-docker.pkg.dev/courtiq-backend/api-gateway/api-gateway:IMAGE_TAG
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: SERVICE_NAME
          value: api-gateway
        - name: DOCKER_ENV
          value: 'true'
        - name: NODE_ENV
          value: production
        - name: GRAPHQL_PLAYGROUND
          value: 'true'
        - name: LOG_LEVEL
          value: warn
        - name: API_GATEWAY_URL
          value: https://api-gateway-zgctp7qz3q-uc.a.run.app
        - name: USER_SERVICE_URL
          value: https://user-service-zgctp7qz3q-uc.a.run.app
        - name: RELATIONSHIP_SERVICE_URL
          value: https://relationship-service-zgctp7qz3q-uc.a.run.app
        - name: MATCHUP_SERVICE_URL
          value: https://matchup-service-zgctp7qz3q-uc.a.run.app
        - name: EQUIPMENT_SERVICE_URL
          value: https://equipment-service-zgctp7qz3q-uc.a.run.app
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: MONGODB_URL
        - name: FIREBASE_CONFIG
          valueFrom:
            secretKeyRef:
              key: latest
              name: FIREBASE_CONFIG
        - name: FIREBASE_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              key: latest
              name: FIREBASE_SERVICE_ACCOUNT
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000
  traffic:
  - percent: 100
    latestRevision: true

