extend type Query {
  """
  Retrieve a specific coaching relationship by ID
  """
  coachship(id: ID!): Coachship

  myCoaches(limit: Int, offset: Int): [Coachship!]!

  myStudents(limit: Int, offset: Int): [Coachship!]!

  myStudentRequests: [Coachship!]!

  myCoachRequests: [Coachship!]!

  sentCoachRequests: [Coachship!]!

  sentStudentRequests: [Coachship!]!
  
  isStudent(studentId: ID!): RelationshipStatus
  
  isCoach(coachId: ID!): RelationshipStatus
}
