apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- api-gateway.yaml
- user-service.yaml
- string-service.yaml
- matchup-service.yaml
- relationship-service.yaml