# graph/schema/schema.gql
scalar DateTime

type Query {
    _empty: String # Placeholder to satisfy empty Query type error
}

type Mutation {
    _empty: String # Placeholder to satisfy empty Mutation type error
}