package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/chat-service/graph/model"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context, id primitive.ObjectID, limit *int, offset *int) ([]model.Message, error) {
	panic(fmt.Errorf("not implemented: Messages - messages"))
}
