input TennisStringInput {
    name: String!
    gauge: StringGauge
    stringingDate: DateTime
    burstDate: DateTime
    tension: StringTensionInput
}

input StringTensionInput {
    mains: Int       # Tension for the mains
    crosses: Int     # Tension for the crosses
}