input CreateTennisRacketInput {
    name: String!
    brand: String
    model: String
    weight: Float
    
}

input UpdateTennisRacketInput {
    name: String
    brand: String
    model: String
    weight: Float
}

input CreateTennisStringInput {
    name: String!
    brand: String
    model: String
    tension: StringTensionInput
    stringingDate: DateTime
    burstDate: DateTime
    racket: ObjectID
}

input UpdateTennisStringInput {
    name: String
    brand: String
    model: String
    tension: StringTensionInput
    stringingDate: DateTime
    burstDate: DateTime
}

input StringTensionInput {
    mains: Int       # Tension for the mains
    crosses: Int     # Tension for the crosses
}