input CreateTennisRacketInput {
    name: String!
    brand: String
    brandId: Int
    model: String
    modelId: Int
    weight: Float
    visibility: Visibility
}

input UpdateTennisRacketInput {
    name: String
    brand: String
    brandId: Int
    model: String
    modelId: Int
    weight: Float
    visibility: Visibility
}

input CreateTennisStringInput {
    name: String!
    brand: String
    brandId: Int
    model: String
    modelId: Int
    tension: StringTensionInput
    stringingDate: DateTime
    burstDate: DateTime
    visibility: Visibility
}

input UpdateTennisStringInput {
    name: String
    brand: String
    brandId: Int
    model: String
    modelId: Int
    tension: StringTensionInput
    stringingDate: DateTime
    burstDate: DateTime
    visibility: Visibility
}

input StringTensionInput {
    mains: Int       # Tension for the mains
    crosses: Int     # Tension for the crosses
}