# Friendship relationship between two users
type Friendship implements Relationship @key(fields: "id") {
  id: ObjectID!
  type: RelationshipType!
  status: RelationshipStatus!
  initiatorId: ObjectID!
  receiverId: ObjectID!
  createdAt: DateTime!
  updatedAt: DateTime
}