type Friendship implements Relationship {
  id: ID!
  participantIds: [ID!]!
  type: RelationshipType!
  status: RelationshipStatus!
  createdAt: String!
  updatedAt: String
  metadata: RelationshipMetadata

  requesterId: ID!
  receiverId: ID!
}
