extend type Query {
    # Racket Queries
    myTennisRacket(id: ObjectID!): TennisRacket
    myStringHistory(racket: ObjectID!): [TennisString!]!

    # String Queries
    myTennisString(id: ObjectID!): TennisString

    # Combined Equipment Query
    myEquipment(limit: Int = 10, offset: Int = 0): [Equipment!]!
}
