package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.53

import (
	"context"

	"github.com/CourtIQ/courtiq-backend/user-service/graph"
	"github.com/CourtIQ/courtiq-backend/user-service/graph/model"
	"github.com/CourtIQ/courtiq-backend/user-service/providers"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	user, err := r.UserService.FindUserByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user, err := r.UserService.FetchCurrentUser(ctx)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// IsUsernameAvailable is the resolver for the isUsernameAvailable field.
func (r *queryResolver) IsUsernameAvailable(ctx context.Context, username string) (bool, error) {
	available, err := r.UserService.IsUsernameAvailable(ctx, username)
	if err != nil {
		return false, err
	}
	return available, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver {
	return &queryResolver{UserService: r.UserService}
}

type queryResolver struct {
	UserService providers.UserServiceProvider
}
