
input UpdateUserInput { 
  firstName: String
  lastName: String
  displayName: String
  dateOfBirth: Time
  bio: String
  location: LocationInput
}

input LocationInput {
  city: String
  state: String
  country: String
  latitude: Float
  longitude: Float
}