
input UpdateUserInput { 
  username: String
  firstName: String
  lastName: String
  gender: Gender
  dateOfBirth: DateTime
  bio: String
  location: LocationInput
  fcmTokens: [String]
}

input LocationInput {
  city: String
  state: String
  country: String
  latitude: Float
  longitude: Float
}