version: '3.9'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - ./api-gateway/.env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"  # Use default 3000 if PORT is not set
    networks:
      - court-iq-network

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    env_file:
      - ./user-service/.env
    ports:
      - "${PORT:-8081}:${INTERNAL_PORT:-8080}"  # Use 8081:8080 as default
    networks:
      - court-iq-network

  relationship-service:
    build:
      context: .
      dockerfile: relationship-service/Dockerfile
    env_file:
      - ./relationship-service/.env
    ports:
      - "${PORT:-8082}:${INTERNAL_PORT:-8080}"
    networks:
      - court-iq-network

  matchup-service:
    build:
      context: .
      dockerfile: matchup-service/Dockerfile
    env_file:
      - ./matchup-service/.env
    ports:
      - "${PORT:-8083}:${INTERNAL_PORT:-8080}"
    networks:
      - court-iq-network

  equipment-service:
    build:
      context: .
      dockerfile: equipment-service/Dockerfile
    env_file:
      - ./equipment-service/.env
    ports:
      - "${PORT:-8084}:${INTERNAL_PORT:-8080}"
    networks:
      - court-iq-network
  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    env_file:
      - ./search-service/.env
    ports:
      - "${PORT:-8085}:${INTERNAL_PORT:-8080}"
    networks:
      - court-iq-network

networks:
  court-iq-network:
    driver: bridge
