version: '3.9'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    env_file:
      - ./api-gateway/.env
    ports:
      - "${API_GATEWAY_PORT:-3000}:3000"
    networks:
      - court-iq-network
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    env_file:
      - ./user-service/.env
    ports:
      - "${USER_SERVICE_PORT:-8081}:8080"
    networks:
      - court-iq-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  relationship-service:
    build:
      context: .
      dockerfile: relationship-service/Dockerfile
    env_file:
      - ./relationship-service/.env
    ports:
      - "${RELATIONSHIP_SERVICE_PORT:-8082}:8080"
    networks:
      - court-iq-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  matchup-service:
    build:
      context: .
      dockerfile: matchup-service/Dockerfile
    env_file:
      - ./matchup-service/.env
    ports:
      - "${MATCHUP_SERVICE_PORT:-8083}:8080"
    networks:
      - court-iq-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  equipment-service:
    build:
      context: .
      dockerfile: equipment-service/Dockerfile
    env_file:
      - ./equipment-service/.env
    ports:
      - "${EQUIPMENT_SERVICE_PORT:-8084}:8080"
    networks:
      - court-iq-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  search-service:
    build:
      context: .
      dockerfile: search-service/Dockerfile
    env_file:
      - ./search-service/.env
    ports:
      - "${SEARCH_SERVICE_PORT:-8085}:8080"
    networks:
      - court-iq-network
    depends_on:
      - api-gateway
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  court-iq-network:
    driver: bridge