// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type StringEntry struct {
	ID                  string `json:"id"`
	UserID              string `json:"userID"`
	StringName          string `json:"stringName"`
	RacketName          string `json:"racketName"`
	StringingDate       string `json:"stringingDate"`
	StringMainsTension  int    `json:"stringMainsTension"`
	StringCrossTensions int    `json:"stringCrossTensions"`
	LastUpdated         string `json:"lastUpdated"`
	EntryDate           string `json:"entryDate"`
}

func (StringEntry) IsEntity() {}

type StringEntryInput struct {
	UserID              string `json:"userID"`
	StringName          string `json:"stringName"`
	RacketName          string `json:"racketName"`
	StringingDate       string `json:"stringingDate"`
	StringMainsTension  int    `json:"stringMainsTension"`
	StringCrossTensions int    `json:"stringCrossTensions"`
	EntryDate           string `json:"entryDate"`
}
