"""
Used to create a new tennis match with the specified type, format, and participants.
If 'visibility' is not provided, it defaults to 'PRIVATE'.
"""
input InitiateMatchUpInput {
  """
  The type of match, e.g., SINGLES or DOUBLES.
  """
  matchUpType: MatchUpType!

  """
  The format and rules for this match (sets, tiebreak details, etc.).
  """
  matchUpFormat: MatchUpFormatInput!

  """
  The players or teams participating in the match.
  """
  participants: [ParticipantInput!]!

  """
  A person who might not be a participant in a match but is helping to track it.
  """
  matchUpTracker: ObjectID!

  """
  The participant (by ObjectID) who will serve first.
  """
  initialServer: ObjectID!

  """
  The style of tracking make used to record match data.
  """
  trackingStyle: MatchUpTrackingStyle = BEGINNER
}
