input MatchUpFormatInput {
    tracker: ObjectID!
    # The id of the tracker should always be the same as `GetMongoID`
    # This does not hold true for createMatchUp mutation
    numberOfSets: NumberOfSets!
    setFormat: SetFormatInput!
    finalSetFormat: SetFormatInput  # TODO Why is passing FinaSetFormat is necessary when creating a match up?
}

input SetFormatInput {
    numberOfGames: NumberOfGames!
    deuceType: DeuceType!
    mustWinByTwo: Boolean!
    tiebreakFormat: TiebreakFormatInput
    tiebreakAt: Int
}

input TiebreakFormatInput {
    points: TiebreakPoints!
    mustWinByTwo: Boolean!
}

input ParticipantsMapInput {
    A: [ObjectID!]!
    B: [ObjectID!]!
}