type MatchUp {
    id: ObjectID!
    matchUpFormat: MatchUpFormat!
    matchUpStatus: MatchUpStatus!
    matchUpType: MatchUpType!

    participantIds: [ObjectID!]!
    participants: ParticipantsMap!

    currentSetIndex: Int
    currentGameIndexWithinSet: Int
    currentPointIndexWithinGame: Int
    currentScore: Score
    currentServer: ObjectID!

    pointsSequence: [ObjectID!]!

    startTime: DateTime!
    endTime: DateTime
    createdAt: DateTime!
    updatedAt: DateTime!
}

type ParticipantsMap {
    A: ObjectID!
    B: ObjectID!
}