type MatchUp {
    id: ObjectID!
    matchUpFormat: MatchUpFormat!
    matchUpStatus: MatchUpStatus!
    matchUpType: MatchUpType!

    participantIds: [ObjectID!]!
    participants: ParticipantsMap!

    currentSetIndex: Int
    currentGameIndexWithinSet: Int
    currentPointIndexWithinGame: Int
    currentScore: Score
    currentServer: ObjectID!
    initalServer: ObjectID!
    # In tennis the server in singles changes after every game
    # In doubles, if i start serving i will server after 3 games,
    # Every fourth game i will server if i am inital server.

    pointsSequence: [ObjectID!]!

    startTime: DateTime!
    endTime: DateTime
    createdAt: DateTime!
    updatedAt: DateTime!
}

type ParticipantsMap {
    A: ObjectID!
    B: ObjectID!
}