type MatchUpPoint {
    id: ObjectID!
    matchUpId: ObjectID!
    winner: TeamSide!
    loser: TeamSide!

    server: Participant!

    timestamp: DateTime,


    # shots: [Shot!]!
}

type MatchUpShot {
    shotType: ShotType!
}