##################
# MatchUpFormat  
##################

type MatchUpFormat {
  id: ObjectID!
  tracker: ObjectID!
  numberOfSets: NumberOfSets!
  setFormat: SetFormat!
  finalSetFormat: SetFormat
  initialServer: ObjectID!
  # TODO: Need to change `initialServer` to accomodate for doubles
}

type SetFormat {
  numberOfGames: NumberOfGames!
  deuceType: DeuceType!
  mustWinByTwo: Boolean!
  tiebreakFormat: TiebreakFormat
  tiebreakAt: Int
}

type TiebreakFormat {
  points: TiebreakPoints!
  mustWinByTwo: Boolean!
}
