##################
# Score
##################

type Score {
  a: SideScore!
  b: SideScore!
}

type SideScore {
  player: ObjectID!
  currentPointScore: GameScore!
  currentGameScore: Int!
  currentSetScore: Int!
  currentTiebreakScore: Int
}