input ExistenceConditions {
  relationshipStatus: RelationshipStatus
  relationshipType: RelationshipType
}

input RoleConditions {
  requireParticipants: Boolean
  requireSender: Boolean
  requireReceiver: Boolean
  requireStudent: Boolean
  requireCoach: Boolean
}

input NonExistenceConditions {
  noExistingFriendship: Boolean
  notExistingCoach: Boolean
  notExistingStudent: Boolean
}

input SatisfiesConditions {
  existence: ExistenceConditions
  roles: RoleConditions
  nonExistence: NonExistenceConditions
}

directive @satisfies(conditions: SatisfiesConditions!) on FIELD_DEFINITION
