package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/relationship-service/graph"
	"github.com/CourtIQ/courtiq-backend/relationship-service/graph/model"
)

// SendCoachRequest is the resolver for the sendCoachRequest field.
func (r *mutationResolver) SendCoachRequest(ctx context.Context, userID string) (*model.Coachship, error) {
	panic(fmt.Errorf("not implemented: SendCoachRequest - sendCoachRequest"))
}

// SendCoacheeRequest is the resolver for the sendCoacheeRequest field.
func (r *mutationResolver) SendCoacheeRequest(ctx context.Context, userID string) (*model.Coachship, error) {
	panic(fmt.Errorf("not implemented: SendCoacheeRequest - sendCoacheeRequest"))
}

// AcceptCoachRequest is the resolver for the acceptCoachRequest field.
func (r *mutationResolver) AcceptCoachRequest(ctx context.Context, coachshipID string) (*model.Coachship, error) {
	panic(fmt.Errorf("not implemented: AcceptCoachRequest - acceptCoachRequest"))
}

// AcceptCoacheeRequest is the resolver for the acceptCoacheeRequest field.
func (r *mutationResolver) AcceptCoacheeRequest(ctx context.Context, coachshipID string) (*model.Coachship, error) {
	panic(fmt.Errorf("not implemented: AcceptCoacheeRequest - acceptCoacheeRequest"))
}

// DeclineCoachRequest is the resolver for the declineCoachRequest field.
func (r *mutationResolver) DeclineCoachRequest(ctx context.Context, coachshipID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeclineCoachRequest - declineCoachRequest"))
}

// DeclineCoacheeRequest is the resolver for the declineCoacheeRequest field.
func (r *mutationResolver) DeclineCoacheeRequest(ctx context.Context, coachshipID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeclineCoacheeRequest - declineCoacheeRequest"))
}

// CancelCoachRequest is the resolver for the cancelCoachRequest field.
func (r *mutationResolver) CancelCoachRequest(ctx context.Context, coachshipID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: CancelCoachRequest - cancelCoachRequest"))
}

// CancelCoacheeRequest is the resolver for the cancelCoacheeRequest field.
func (r *mutationResolver) CancelCoacheeRequest(ctx context.Context, coachshipID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: CancelCoacheeRequest - cancelCoacheeRequest"))
}

// EndCoachship is the resolver for the endCoachship field.
func (r *mutationResolver) EndCoachship(ctx context.Context, coachshipID string) (*bool, error) {
	panic(fmt.Errorf("not implemented: EndCoachship - endCoachship"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
