package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"github.com/CourtIQ/courtiq-backend/relationship-service/graph"
	"github.com/CourtIQ/courtiq-backend/relationship-service/graph/model"
)

// Coachship is the resolver for the coachship field.
func (r *queryResolver) Coachship(ctx context.Context, id string) (*model.Coachship, error) {
	return r.RelationshipService.GetCoachship(ctx, id)
}

// MyCoaches is the resolver for the myCoaches field.
func (r *queryResolver) MyCoaches(ctx context.Context, limit *int, offset *int) ([]*model.Coachship, error) {
	return r.RelationshipService.ListCoaches(ctx, limit, offset)
}

// MyStudents is the resolver for the myStudents field.
func (r *queryResolver) MyStudents(ctx context.Context, limit *int, offset *int) ([]*model.Coachship, error) {
	return r.RelationshipService.ListStudents(ctx, limit, offset)
}

// MyStudentRequests is the resolver for the myStudentRequests field.
func (r *queryResolver) MyStudentRequests(ctx context.Context) ([]*model.Coachship, error) {
	return r.RelationshipService.ListReceivedStudentRequests(ctx)
}

// MyCoachRequests is the resolver for the myCoachRequests field.
func (r *queryResolver) MyCoachRequests(ctx context.Context) ([]*model.Coachship, error) {
	return r.RelationshipService.ListReceivedCoachRequests(ctx)
}

// SentCoachRequests is the resolver for the sentCoachRequests field.
func (r *queryResolver) SentCoachRequests(ctx context.Context) ([]*model.Coachship, error) {
	return r.RelationshipService.ListSentCoachRequests(ctx)
}

// SentStudentRequests is the resolver for the sentStudentRequests field.
func (r *queryResolver) SentStudentRequests(ctx context.Context) ([]*model.Coachship, error) {
	return r.RelationshipService.ListSentStudentRequests(ctx)
}

// IsStudent is the resolver for the isStudent field.
func (r *queryResolver) IsStudent(ctx context.Context, studentID string) (*model.RelationshipStatus, error) {
	return r.RelationshipService.IsStudent(ctx, studentID)
}

// IsCoach is the resolver for the isCoach field.
func (r *queryResolver) IsCoach(ctx context.Context, coachID string) (*model.RelationshipStatus, error) {
	return r.RelationshipService.IsCoach(ctx, coachID)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
