package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/relationship-service/graph"
	"github.com/CourtIQ/courtiq-backend/relationship-service/graph/model"
)

// FindCoachshipByID is the resolver for the findCoachshipByID field.
func (r *entityResolver) FindCoachshipByID(ctx context.Context, id string) (*model.Coachship, error) {
	return r.RelationshipService.GetCoachship(ctx, id)
}

// FindFriendshipByID is the resolver for the findFriendshipByID field.
func (r *entityResolver) FindFriendshipByID(ctx context.Context, id string) (*model.Friendship, error) {
	return r.RelationshipService.GetFriendship(ctx, id)
}

// FindRelationshipByID is the resolver for the findRelationshipByID field.
func (r *entityResolver) FindRelationshipByID(ctx context.Context, id string) (model.Relationship, error) {
	if coachship, err := r.RelationshipService.GetCoachship(ctx, id); err == nil {
		return coachship, nil
	}
	if friendship, err := r.RelationshipService.GetFriendship(ctx, id); err == nil {
		return friendship, nil
	}
	return nil, fmt.Errorf("relationship with ID %s not found", id)
}

// Entity returns graph.EntityResolver implementation.
func (r *Resolver) Entity() graph.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
