package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"

	"github.com/CourtIQ/courtiq-backend/relationship-service/graph"
	"github.com/CourtIQ/courtiq-backend/relationship-service/graph/model"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// FindCoachshipByID is the resolver for the findCoachshipByID field.
func (r *entityResolver) FindCoachshipByID(ctx context.Context, id primitive.ObjectID) (*model.Coachship, error) {
	return r.RelationshipServiceIntf.FindCoachshipByID(ctx, id)
}

// FindFriendshipByID is the resolver for the findFriendshipByID field.
func (r *entityResolver) FindFriendshipByID(ctx context.Context, id primitive.ObjectID) (*model.Friendship, error) {
	return r.RelationshipServiceIntf.FindFriendshipByID(ctx, id)
}

// FindRelationshipByID is the resolver for the findRelationshipByID field.
func (r *entityResolver) FindRelationshipByID(ctx context.Context, id primitive.ObjectID) (model.Relationship, error) {
	return r.RelationshipServiceIntf.FindRelationshipByID(ctx, id)
}

// Entity returns graph.EntityResolver implementation.
func (r *Resolver) Entity() graph.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
