package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"github.com/CourtIQ/courtiq-backend/relationship-service/graph/model"
)

// Friendship is the resolver for the friendship field.
func (r *queryResolver) Friendship(ctx context.Context, id string) (*model.Friendship, error) {
	return r.RelationshipService.GetFriendship(ctx, id)
}

// MyFriends is the resolver for the myFriends field.
func (r *queryResolver) MyFriends(ctx context.Context, limit *int, offset *int) ([]*model.Friendship, error) {
	return r.RelationshipService.ListMyFriends(ctx, *limit, *offset)
}

// Friends is the resolver for the friends field.
func (r *queryResolver) Friends(ctx context.Context, ofUserID *string, limit *int, offset *int) ([]*model.Friendship, error) {
	return r.RelationshipService.ListFriends(ctx, *ofUserID, *limit, *offset)
}

// MyFriendRequests is the resolver for the myFriendRequests field.
func (r *queryResolver) MyFriendRequests(ctx context.Context) ([]*model.Friendship, error) {
	return r.RelationshipService.ListFriendRequests(ctx)
}

// SentFriendRequests is the resolver for the sentFriendRequests field.
func (r *queryResolver) SentFriendRequests(ctx context.Context) ([]*model.Friendship, error) {
	return r.RelationshipService.ListSentFriendRequests(ctx)
}

// FriendshipStatus is the resolver for the friendshipStatus field.
func (r *queryResolver) FriendshipStatus(ctx context.Context, otherUserID string) (*model.RelationshipStatus, error) {
	return r.RelationshipService.CheckFriendshipStatus(ctx, otherUserID)
}
