"""
Represents the possible status of a relationship between users.
"""
enum RelationshipStatus {
  """
  The relationship is in a pending state, meaning a request has been sent but not yet accepted.
  """
  PENDING

  """
  The relationship is active, meaning the request has been accepted and the relationship is established.
  """
  ACTIVE
}