package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"context"

	"github.com/CourtIQ/courtiq-backend/search-service/graph"
	"github.com/CourtIQ/courtiq-backend/search-service/graph/model"
)

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string, resourceTypes []model.ResourceType, limit *int, offset *int) ([]model.SearchResult, error) {
	return r.SearchService.Search(ctx, query, resourceTypes, limit, offset)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
