version: '3'

services:
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: ${API_GATEWAY_NAME}
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    env_file:
      - .env.populated
    depends_on:
      - user-service
      - string-service
      - matchup-service
      - relationship-service
    networks:
      - backend-network

  user-service:
    build:
      context: ../user-service
      dockerfile: ../deploy/Dockerfile
      args:
        SERVICE_NAME: user-service
        SERVICE_PORT: ${USER_SERVICE_PORT}  # Pass at build time
    container_name: ${USER_SERVICE_NAME}
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"  # Expose the correct port
    env_file:
      - .env.populated
    environment:
      - PORT=${USER_SERVICE_PORT}  # Map USER_SERVICE_PORT to PORT
    networks:
      - backend-network

  string-service:
    build:
      context: ../string-service
      dockerfile: ../deploy/Dockerfile
      args:
        SERVICE_NAME: string-service
        SERVICE_PORT: ${STRING_SERVICE_PORT}
    container_name: ${STRING_SERVICE_NAME}
    ports:
      - "${STRING_SERVICE_PORT}:${STRING_SERVICE_PORT}"
    env_file:
      - .env.populated
    environment:
      - PORT=${STRING_SERVICE_PORT}  # Map STRING_SERVICE_PORT to PORT
    networks:
      - backend-network

  matchup-service:
    build:
      context: ../matchup-service
      dockerfile: ../deploy/Dockerfile
      args:
        SERVICE_NAME: matchup-service
        SERVICE_PORT: ${MATCHUP_SERVICE_PORT}
    container_name: ${MATCHUP_SERVICE_NAME}
    ports:
      - "${MATCHUP_SERVICE_PORT}:${MATCHUP_SERVICE_PORT}"
    env_file:
      - .env.populated
    environment:
      - PORT=${MATCHUP_SERVICE_PORT}  # Map MATCHUP_SERVICE_PORT to PORT
    networks:
      - backend-network

  relationship-service:
    build:
      context: ../relationship-service
      dockerfile: ../deploy/Dockerfile
      args:
        SERVICE_NAME: relationship-service
        SERVICE_PORT: ${RELATIONSHIP_SERVICE_PORT}
    container_name: ${RELATIONSHIP_SERVICE_NAME}
    ports:
      - "${RELATIONSHIP_SERVICE_PORT}:${RELATIONSHIP_SERVICE_PORT}"
    env_file:
      - .env.populated
    environment:
      - PORT=${RELATIONSHIP_SERVICE_PORT}  # Map RELATIONSHIP_SERVICE_PORT to PORT
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
