# Tennis Racket Type
type TennisRacket implements Equipment @key(fields: "id") {
    id: ObjectID!                         # Unique identifier for the racket
    ownerId: ObjectID!                    # Owner's ID (user)
    name: String!                         # Name of the racket
    type: EquipmentType!                  # Equipment type (e.g., TENNIS_RACKET)
    createdAt: DateTime!                  # Timestamp for when the racket was created
    updatedAt: DateTime!                  # Timestamp for the last update
    visibility: Visibility                # Visibility of the racket (PUBLIC, PRIVATE, FRIENDS)


    # Racket-specific fields
    currentStringId: ObjectID             # ID of the current string setup for the racket, optional
    brand: String                         # Brand of the racket (e.g., Wilson, Babolat)
    brandId: Int                          # Brand ID for the racket (optional)    
    model: String                         # Model of the racket (e.g., Blade 98)
    modelId: Int                          # Model ID for the racket (optional)
    weight: Float                         # Weight of the racket in grams (e.g., 305.0)
}

extend type User @key(fields: "id") {
    id: ObjectID! @external
    myTennisRackets(limit: Int = 10, offset: Int = 0): [TennisRacket!]! @requires(fields: "id")
    myTennisStrings(limit: Int = 10, offset: Int = 0): [TennisString!]! @requires(fields: "id")
}