package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.53

import (
	"context"
	"fmt"

	"github.com/CourtIQ/backend-courtiq/string-service/graph"
	"github.com/CourtIQ/backend-courtiq/string-service/graph/model"
)

// CreateStringEntry is the resolver for the createStringEntry field.
func (r *mutationResolver) CreateStringEntry(ctx context.Context, input model.StringEntryInput) (*model.StringEntry, error) {
	panic(fmt.Errorf("not implemented: CreateStringEntry - createStringEntry"))
}

// UpdateStringEntry is the resolver for the updateStringEntry field.
func (r *mutationResolver) UpdateStringEntry(ctx context.Context, id string, input model.StringEntryInput) (*model.StringEntry, error) {
	panic(fmt.Errorf("not implemented: UpdateStringEntry - updateStringEntry"))
}

// DeleteStringEntry is the resolver for the deleteStringEntry field.
func (r *mutationResolver) DeleteStringEntry(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteStringEntry - deleteStringEntry"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
