package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"github.com/CourtIQ/courtiq-backend/equipment-service/graph"
	"github.com/CourtIQ/courtiq-backend/equipment-service/graph/model"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// MyTennisRackets is the resolver for the myTennisRackets field.
func (r *queryResolver) MyTennisRackets(ctx context.Context, limit *int, offset *int) ([]*model.TennisRacket, error) {
	return r.EquipmentServiceIntf.MyTennisRackets(ctx, limit, offset)
}

// MyTennisRacket is the resolver for the myTennisRacket field.
func (r *queryResolver) MyTennisRacket(ctx context.Context, id primitive.ObjectID) (*model.TennisRacket, error) {
	return r.EquipmentServiceIntf.MyTennisRacket(ctx, id)
}

// MyTennisStrings is the resolver for the myTennisStrings field.
func (r *queryResolver) MyTennisStrings(ctx context.Context, limit *int, offset *int) ([]*model.TennisString, error) {
	return r.EquipmentServiceIntf.MyTennisStrings(ctx, limit, offset)
}

// MyTennisString is the resolver for the myTennisString field.
func (r *queryResolver) MyTennisString(ctx context.Context, id primitive.ObjectID) (*model.TennisString, error) {
	return r.EquipmentServiceIntf.MyTennisString(ctx, id)
}

// MyEquipment is the resolver for the myEquipment field.
func (r *queryResolver) MyEquipment(ctx context.Context, limit *int, offset *int) ([]model.Equipment, error) {
	return r.EquipmentServiceIntf.MyEquipment(ctx, limit, offset)
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
