package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/equipment-service/graph"
	"github.com/CourtIQ/courtiq-backend/equipment-service/graph/model"
)

// AddTennisRacket is the resolver for the addTennisRacket field.
func (r *mutationResolver) AddTennisRacket(ctx context.Context, input model.TennisRacketInput) (*model.TennisRacket, error) {
	panic(fmt.Errorf("not implemented: AddTennisRacket - addTennisRacket"))
}

// UpdateTennisRacket is the resolver for the updateTennisRacket field.
func (r *mutationResolver) UpdateTennisRacket(ctx context.Context, id string, input model.TennisRacketInput) (*model.TennisRacket, error) {
	panic(fmt.Errorf("not implemented: UpdateTennisRacket - updateTennisRacket"))
}

// DeleteTennisRacket is the resolver for the deleteTennisRacket field.
func (r *mutationResolver) DeleteTennisRacket(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTennisRacket - deleteTennisRacket"))
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
