package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/equipment-service/graph/model"
)

// AddTennisString is the resolver for the addTennisString field.
func (r *mutationResolver) AddTennisString(ctx context.Context, input model.TennisStringInput) (*model.TennisString, error) {
	panic(fmt.Errorf("not implemented: AddTennisString - addTennisString"))
}

// UpdateTennisString is the resolver for the updateTennisString field.
func (r *mutationResolver) UpdateTennisString(ctx context.Context, id string, input model.TennisStringInput) (*model.TennisString, error) {
	panic(fmt.Errorf("not implemented: UpdateTennisString - updateTennisString"))
}

// DeleteTennisString is the resolver for the deleteTennisString field.
func (r *mutationResolver) DeleteTennisString(ctx context.Context, id string) (*bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTennisString - deleteTennisString"))
}

// AssignStringToRacket is the resolver for the assignStringToRacket field.
func (r *mutationResolver) AssignStringToRacket(ctx context.Context, racketID string, stringID string) (*model.TennisRacket, error) {
	panic(fmt.Errorf("not implemented: AssignStringToRacket - assignStringToRacket"))
}
