package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/equipment-service/graph"
	"github.com/CourtIQ/courtiq-backend/equipment-service/graph/model"
)

// MyRackets is the resolver for the myRackets field.
func (r *queryResolver) MyRackets(ctx context.Context) ([]*model.TennisRacket, error) {
	panic(fmt.Errorf("not implemented: MyRackets - myRackets"))
}

// GetRacket is the resolver for the getRacket field.
func (r *queryResolver) GetRacket(ctx context.Context, id string) (*model.TennisRacket, error) {
	panic(fmt.Errorf("not implemented: GetRacket - getRacket"))
}

// MyCurrentRacket is the resolver for the myCurrentRacket field.
func (r *queryResolver) MyCurrentRacket(ctx context.Context) (*model.TennisRacket, error) {
	panic(fmt.Errorf("not implemented: MyCurrentRacket - myCurrentRacket"))
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
