package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/equipment-service/graph/model"
)

// MyStrings is the resolver for the myStrings field.
func (r *queryResolver) MyStrings(ctx context.Context) ([]*model.TennisString, error) {
	panic(fmt.Errorf("not implemented: MyStrings - myStrings"))
}

// GetTennisStringByID is the resolver for the getTennisStringById field.
func (r *queryResolver) GetTennisStringByID(ctx context.Context, id string) (*model.TennisString, error) {
	panic(fmt.Errorf("not implemented: GetTennisStringByID - getTennisStringById"))
}
