
type Location {
    """Name of the city."""
    city: String
    """Name of the state or province."""
    state: String
    """Name of the country."""
    country: String
    """Geographical latitude coordinate."""
    latitude: Float
    """Geographical longitude coordinate."""
    longitude: Float
}
