extend type Query {
    testNumberOfSets(sets: NumberOfSets): NumberOfSets!
    testNumberOfGames(games: NumberOfGames): NumberOfGames!
    testTiebreakPoints(games: TiebreakPoints): TiebreakPoints!
}