package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.61

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/matchup-service/graph/model"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// AddShot is the resolver for the addShot field.
func (r *mutationResolver) AddShot(ctx context.Context, input model.AddShotInput) (*model.MatchUpShot, error) {
	panic(fmt.Errorf("not implemented: AddShot - addShot"))
}

// UndoLastShot is the resolver for the undoLastShot field.
func (r *mutationResolver) UndoLastShot(ctx context.Context, matchUpID primitive.ObjectID) (*model.MatchUpShot, error) {
	panic(fmt.Errorf("not implemented: UndoLastShot - undoLastShot"))
}

// RedoShot is the resolver for the redoShot field.
func (r *mutationResolver) RedoShot(ctx context.Context, matchUpID primitive.ObjectID) (*model.MatchUpShot, error) {
	panic(fmt.Errorf("not implemented: RedoShot - redoShot"))
}
