package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/CourtIQ/courtiq-backend/matchup-service/graph/model"
)

// MatchUpFormat is the resolver for the matchUpFormat field.
func (r *queryResolver) MatchUpFormat(ctx context.Context, id string) (*model.MatchUpFormat, error) {
	panic(fmt.Errorf("not implemented: MatchUpFormat - matchUpFormat"))
}

// DefaultMatchUpFormats is the resolver for the defaultMatchUpFormats field.
func (r *queryResolver) DefaultMatchUpFormats(ctx context.Context) ([]*model.MatchUpFormat, error) {
	panic(fmt.Errorf("not implemented: DefaultMatchUpFormats - defaultMatchUpFormats"))
}
