enum ResourceType {
  USER
  TENNIS_COURTS
}

union SearchResult = UserSearchResult | TennisCourtSearchResult

extend type Query {
  search(
    query: String!
    resourceTypes: [ResourceType!] = [USER]
    limit: Int = 5
    offset: Int = 0
    near: GeoPoint
  ): [SearchResult!]!

  searchTennisCourts(
    query: String!
    limit: Int = 5
    offset: Int = 0
    near: GeoPoint
  ): [TennisCourtSearchResult!]!

  searchUsers(
    query: String!
    limit: Int = 5
    offset: Int = 0
  ): [UserSearchResult!]!
}

extend type Mutation {
  favouriteCourt(courtId: ObjectID!): Boolean!
  removeCourtFromFavorites(courtId: ObjectID!): Boolean!
}
