apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: matchup-service
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/ingress: internal
        run.googleapis.com/ingress-status: internal
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1080781728713-compute@developer.gserviceaccount.com
      containers:
      - name: matchup-service
        image: us-central1-docker.pkg.dev/courtiq-backend/matchup-service/matchup-service:IMAGE_TAG
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: matchup-service
        - name: DOCKER_ENV
          value: 'true'
        - name: NODE_ENV
          value: production
        - name: GRAPHQL_PLAYGROUND
          value: 'false'
        - name: LOG_LEVEL
          value: warn
        - name: API_GATEWAY_URL
          value: https://api-gateway.court-iq.com
        - name: USER_SERVICE_URL
          value: https://user-service-1080781728713.us-central1.run.app
        - name: RELATIONSHIP_SERVICE_URL
          value: https://relationship-service-1080781728713.us-central1.run.app
        - name: MATCHUP_SERVICE_URL
          value: https://matchup-service-1080781728713.us-central1.run.app
        - name: EQUIPMENT_SERVICE_URL
          value: https://equipment-service-1080781728713.us-central1.run.app
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              key: latest
              name: MONGODB_URL
        - name: FIREBASE_CONFIG
          valueFrom:
            secretKeyRef:
              key: latest
              name: FIREBASE_CONFIG
        - name: FIREBASE_SERVICE_ACCOUNT
          valueFrom:
            secretKeyRef:
              key: latest
              name: FIREBASE_SERVICE_ACCOUNT
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
