name: Build and Publish

on:
  push:
    branches:
      - pipeline_build
    tags:
      - '*'

env:
  GCR_IMAGE_LOCATION: us-central1
  GCP_PROJECT_ID: courtiq-backend

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set Environment Variables and Tags
        run: |
          TAG="latest"          
          BRANCH=${{ github.head_ref || github.ref_name }}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo ${{github.ref}} |  cut -d / -f 3)
            BRANCH=$TAG
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCR_IMAGE_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        env:
          SVC_NAME: equipment-service
        uses: docker/build-push-action@v6
        with:
          context: ./${{ env.SVC_NAME }}
          file: ./${{ env.SVC_NAME }}/Dockerfile
          push: true
          tags: ${{ env.GCR_IMAGE_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.SVC_NAME }}/${{ env.SVC_NAME }}:${{ env.TAG }}
