name: Build and Publish

on:
  push:
    branches:
      - pipeline_build
    tags:
      - '*'
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Set Environment Variables and Tags
        run: |
          TAG="latest"          
          BRANCH=${{ github.head_ref || github.ref_name }}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAG=$(echo ${{github.ref}} |  cut -d / -f 3)
            BRANCH=$TAG
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Configure Docker for GCR
        run: |
          echo "Setting up Docker for GCR"
          gcloud auth configure-docker --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./equipment-service
          file: ./equipment-service/Dockerfile
          push: true
          tags: ${{ env.GCR_IMAGE_LOCATION }}-docker.pkg.dev//${{ env.GCP_PROJECT_ID }}/equipment-service/equipment-service:${{ TAG }}
