name: Setup Cloud Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to set up secrets for'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  setup_secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Load secrets from 1Password based on environment
      - name: Load 1Password Secrets for ${{ github.event.inputs.environment }}
        uses: 1Password/load-secrets-action@v2.0.0
        with:
          # Export secrets as environment variables
          export-env: true
          # Set item based on environment
          item: "Court IQ ${{ github.event.inputs.environment }}"
          # List of secrets to load
          secrets: |
            MONGODB_URL
            FIREBASE_CONFIG
            FIREBASE_SERVICE_ACCOUNT
            GOOGLE_PLACES_API_KEY

      - name: Create or Update Google Cloud Secrets
        run: |
          echo "Setting up secrets for ${{ github.event.inputs.environment }} environment..."
          
          # Function to create or update a secret
          create_or_update_secret() {
            local secret_name=$1
            local secret_value=$2
            
            # Check if secret exists
            if gcloud secrets describe $secret_name 2>/dev/null; then
              echo "Updating existing secret: $secret_name"
              echo -n "$secret_value" | gcloud secrets versions add $secret_name --data-file=-
            else
              echo "Creating new secret: $secret_name"
              echo -n "$secret_value" | gcloud secrets create $secret_name --replication-policy="automatic" --data-file=-
            fi
          }
          
          # Create or update each secret
          create_or_update_secret "mongodb-url" "$MONGODB_URL"
          create_or_update_secret "firebase-config" "$FIREBASE_CONFIG"
          create_or_update_secret "firebase-service-account" "$FIREBASE_SERVICE_ACCOUNT"
          create_or_update_secret "google-places-api-key" "$GOOGLE_PLACES_API_KEY"
          
          echo "Secret setup complete!"