name: Test on push

on:
  push:
    branches:
      - '*'

jobs:
  api_gateway:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.3.x'

      - name: Install dependencies, build and test
        run: |
          cd api-gateway
          npm ci
          npm run build --if-present
          npm test

  equipment-service:
    env:
      SVC_NAME: equipment-service
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies and test
        run: |
          cd ${{ env.SVC_NAME }}
          go mod download
          go test ./...

  matchup-service:
    env:
      SVC_NAME: matchup-service
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies and test
        run: |
          cd ${{ env.SVC_NAME }}
          go mod download
          go test ./...

  relationship-service:
    env:
      SVC_NAME: relationship-service
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies and test
        run: |
          cd ${{ env.SVC_NAME }}
          go mod download
          go test ./...

  user-service:
    env:
      SVC_NAME: user-service
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies and test
        run: |
          cd ${{ env.SVC_NAME }}
          go mod download
          go test ./...