name: Test on push

on:
  push:
    branches:
      - '*'

jobs:
  api_gateway:
    env:
      SVC_NAME: api-gateway
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

  equipment_service:
    env:
      SVC_NAME: equipment-service
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test